http:
  addr: "127.0.0.1:8042"

api:
  username: airmon
  password: secure123456
  
sensors:
  sps30:
    enabled: true
    i2c_address: 0x75
    read_interval: 20s
  scd40:
    enabled: true
  bme280:
    enabled: true
  mq2:
    enabled: true