apiVersion: 1

datasources:
  - name: 'prometheus-ds'
    type: 'prometheus'
    access: 'proxy'
    url: 'http://prometheus:9090'
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: "POST"